package net.opmasterleo.license;

public enum LicenseOutcome {
    VALID,
    EXPIRED,
    REVOKED,
    IP_NOT_WHITELISTED,
    HWID_REQUIRED,
    MAX_HWIDS_REACHED,
    BLACKLISTED_IP,
    BLACKLISTED_HWID,
    PRODUCT_MISMATCH,
    PRODUCT_ARCHIVED,
    LICENSE_NOT_FOUND,
    TIMESTAMP_DESYNC,
    RATE_LIMITED,
    SIGNATURE_INVALID,
    NETWORK_ERROR
}
