org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

org.gradle.daemon.idletimeout=600000

org.gradle.jvmargs=-Xmx2g -Xms512m -XX:MaxMetaspaceSize=384m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
